(global-set-key (kbd "C-x C-b")
                (lambda ()
                  (interactive)
                  (let ((buffer-list-window (list-buffers)))
                    (fit-window-to-buffer buffer-list-window)
                    (select-window buffer-list-window)
                    (setq tabulated-list-sort-key '("File"))
                    (tabulated-list-init-header)
                    ; don't try to preserve selection, because...
                    (tabulated-list-print nil)
                    ; ...we're about to place the point at the beginning of
                    ; the line for the selected buffer
                    (if (search-forward "\n." nil t)
                        (forward-char -1))
                    (hl-line-mode t))))
(defun Buffer-menu-quit-and-select ()
  (interactive)
  (Buffer-menu-execute)
  (let ((selected-buffer (Buffer-menu-buffer t)))
    (quit-window)
    (switch-to-buffer selected-buffer)))
(define-key Buffer-menu-mode-map "\C-m" 'Buffer-menu-quit-and-select)
(define-key Buffer-menu-mode-map "j" 'next-line)
(define-key Buffer-menu-mode-map "k" 'previous-line)